from pCrunch import read

"""
This script checks the output files of simulation runs in a specified directory and determines whether 
each simulation completed successfully or failed prematurely.

Modules:
    - pCrunch: Used to read the output binary files (.outb) generated by Fast.Farm.
    - os: Used for directory and file path operations.

Constants:
    - directory (str): The path to the directory containing the simulation case folders.
    - filename (str): The base name of the output file to check.
    - Tmax (int): The expected maximum simulation time. Simulations with a last time step less than this 
      value are considered to have failed prematurely.

Workflow:
    1. List all subdirectories in the specified `directory` path.
    2. Sort the subdirectories numerically based on the suffix of their names (assumes folder names end 
       with an underscore followed by a number).
    3. For each folder:
        - If not run, increment the count of cases that have been run but are missing output files.
            - If the last time step is greater than `Tmax`, increment the count of successful cases.
            - Otherwise, increment the count of failed cases.

    Outputs:
        - Prints the total number of cases.
        - Prints the number of cases that have been run but are missing output files.
        - Prints the number of successful cases.
        - Prints the number of failed cases.

Usage:
    - Update the `directory` variable to point to the directory containing your simulation case folders.
    - Ensure the `filename` variable matches the base name of the output files you want to check.
    - Adjust the `Tmax` variable to reflect the expected maximum simulation time for your use case.
"""
import os

# Inputs
directory = "/Users/pbortolo/work/3_projects/30_HolisticSE/FarmCast_runs/cases"
filename = "generated"
Tmax = 900

# Execution
folders = [f for f in os.listdir(directory) if os.path.isdir(os.path.join(directory, f))]
folders.sort(key=lambda x: int(x.split('_')[-1]))

cases_run = 0
last_case_run = 0
ok_cases = 0
failed_cases = 0

for i in range(len(folders)):
    folder_path = os.path.join(directory, folders[i])
    outb = os.path.join(folder_path, "fastfarm", filename + ".T1.outb")
    if os.path.exists(outb):
        cases_run += 1
        data = read(outb)
        if data["Time"][-1] > Tmax:
            last_case_run = i
            ok_cases += 1
        else:
            failed_cases += 1

print(f"Total number of cases: {len(folders)}")
print(f"Cases run so far: {cases_run}")
print(f"Successful cases: {ok_cases}")
print(f"Not successful cases: {failed_cases}")
print(f"Last successful case: {last_case_run}")
