from pCrunch import read
"""
This script checks the output files of simulation runs in a specified directory and determines whether 
each simulation completed successfully or failed prematurely.

Modules:
    - pCrunch: Used to read the output binary files (.outb) generated by Fast.Farm.
    - os: Used for directory and file path operations.

Constants:
    - directory (str): The path to the directory containing the simulation case folders.
    - filename (str): The base name of the output file to check.
    - Tmax (int): The expected maximum simulation time. Simulations with a last time step less than this 
      value are considered to have failed prematurely.

Workflow:
    1. List all subdirectories in the specified `directory` path.
    2. Sort the subdirectories numerically based on the suffix of their names (assumes folder names end 
       with an underscore followed by a number).
    3. For each folder:
        - Construct the path to the expected output file.
        - Check if the output file exists:
            - If not, print a message indicating the folder was not run or the output file is missing.
            - If it exists, read the output file and check the last time step:
                - If the last time step is greater than `Tmax`, print a message indicating the simulation 
                  completed successfully.
                - Otherwise, print a message indicating the simulation failed prematurely and display the 
                  last time step.

Usage:
    - Update the `directory` variable to point to the directory containing your simulation case folders.
    - Ensure the `filename` variable matches the base name of the output files you want to check.
    - Adjust the `Tmax` variable to reflect the expected maximum simulation time for your use case.
"""
import os

# Inputs
directory = "/Users/pbortolo/work/3_projects/30_HolisticSE/FarmCast_runs/cases"
filename = "generated"
Tmax = 900

# Execution
folders = [f for f in os.listdir(directory) if os.path.isdir(os.path.join(directory, f))]
folders.sort(key=lambda x: int(x.split('_')[-1]))

for folder in folders:
    folder_path = os.path.join(directory, folder)
    outb = os.path.join(folder_path, "fastfarm", filename + ".T1.outb")
    if not os.path.exists(outb):
        print(f"{folder} not run or output file missing")
    else:
        data = read(outb)
        if data["Time"][-1] > Tmax:
            print(f"{folder} completed successfully")
        else:
            print(f"{folder} failed prematurely, last time step: {data['Time'][-1]}")


